package:
  name: tomosaic
  version: '0.0.1'

source:
  path: .
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - h5py
    - scipy <0.15 # [py26]
    - scipy


test:
  # Python imports
  imports:
    - tomosaic

about:
  home: http://tomosaic.readthedocs.org
  license: BSD-3
  summary: 'Mosaic Tomographic reconstruction in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

